"""Adicionando coluna (is_admin) na tabela usuarios

Revision ID: 288f5eb51b3b
Revises: b007cf68c5df
Create Date: 2025-07-23 16:25:38.216935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288f5eb51b3b'
down_revision: Union[str, Sequence[str], None] = 'b007cf68c5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'is_admin')
    # ### end Alembic commands ###
